### PR TITLE
[geocat] change logo to newer version, hide link to new version in login screen

### PR DESCRIPTION
**Pull request by jahow**
Done for https://camptocamp.atlassian.net/browse/GSGCT-122

image

### CODE REVIEW

**Review by cmangeat — COMMENTED** [review]
did you take https://github.com/geoadmin/geocat/commit/b40a7f37c755c714e5f828bf4e2384e2a7a33aea into account ?

gn harvester logos are configurable, the harvester logos are indeed logos of the partners which have to be credited and are of importance in this sense, you probably just have to use the admin ui to update / push the banner to use.

anyway, it should be good to let swisstopo the possibility to do it.

**Comment by Angi-Kinas** [comment]
@cmangeat thanks for the review and good point!
I think we would need to change the css (size of the picture and picture placement) to make it look nice anyway, so I would say we could leave it like this.

**Comment by cmangeat** [comment]
Obviously, there is a test missing ! I.e, leave it like this would mean reopen https://jira.swisstopo.ch/browse/MGEO_SB-888.

**Comment by jahow** [comment]
@cmangeat I have updated the PR, can you please let me know if you approve this? Thanks

**Review by cmangeat — APPROVED** [review]
thanks !

**Pull request merged**
