### PR TITLE
Backport unpublish metadata CRON Job and Reports

### PR DESCRIPTION
**Pull request by fgravin**
Get unpublish tasks, services, reports and jobs from old geocat.
Exports look quite good but can't manage to execute the unpublishMetadata Quartz !!!
The one from archive backup is working fine but can't fix it for unpublishMetadata ...

Please @cmangeat and @fxprunayre can have a look on sprint quartz ScheduleManager and CRON definitions, and look why UnpublishMetadataJob service can't launch it ?
Maybe i missed something.

I've tested to launch it from spring service, and put the Job in same package as backup archive but still the same.

Thanks

### CODE REVIEW

**Comment by fgravin** [comment]
@fxprunayre @cmangeat 

I managed to fix it ..
All `@Autowired` objects were all null so i think the bean was not well initialized.
I removed `Service` interface and moved it to another package. Don't really know what was wrong about Spring init.

I also had an autowired on `ISearchManager` was not working either.

I can now call my Job, still have problem cause `doValide()` needs a session and context.getSession() is null ...
Let's see tomorow.

**Comment by fgravin** [comment]
Ready for quick review

**Comment by fgravin** [comment]
Well it's almost same code as before, but 2 changes cause methods signature have changed `doValidate` and `indexMetadata` with no `SearchManager`, not sure about this.

Maybe just look at the Job class and the call of those 2 methods if it looks good to you.

**Comment by fxprunayre** [comment]
> t 2 changes cause methods signature have changed doValidate and indexMetadata with no SearchManager, not sure about this.

If you don't provide the search manager it will goes to Lucene index. It's used to set a custom SearchManager to index in ES. So it sounds ok.

**Pull request merged**
